### PR TITLE
I scorched the earth now there is a new TABLEFLIP blog

### PR DESCRIPTION
**Pull request by bmordan**
New blog.

Built like the docs project

Might be good to pull, checkout and run the blog on your machine.

Instructions in the readme

### CODE REVIEW

**Comment by alanshaw** [comment]
👓

**Review by alanshaw — CHANGES_REQUESTED** [review]
Looking good!

- [x] Install and start instructions should be:
    ```
    gem install bundler
    bundle install
    bundle exec jekyll serve --watch
    ```
- [x] Multiple styling issues in firefox:
    screen shot 2017-10-03 at 13 17 14
- [x] Posts are not in the correct order

Minor tweaks:

- [x] I think we can lose "time" altogether from the date formatting (same as ghost does)
- [x] Feels like there's too much space between the header and posts list
- [x] TABLEFLIP logo doesn't shrink when scroll off the top of the page
- [x] Please could you style the `<hr/>`s?
- [x] On post pages could you please make the main post title `<h1>` bigger than `<h2>`'s in the page? e.g. http://localhost:4000/meteor-london-june-2014
- [x] Could we lose the `ml3` on the avatar on the post list page - it just looks misaligned?
- [x] I'm not super keen on the border bottom for the post titles on the post list page. Do you think something like this would be cleaner?:
    screen shot 2017-10-03 at 13 27 30
- [x] Prev/next buttons at the bottom of the page aren't equal width...
- [x] Can it auto RSS? https://blog.tableflip.io/rss/

**Comment by bmordan** [comment]
screen shot 2017-10-03 at 16 42 09
screen shot 2017-10-03 at 16 42 26
screen shot 2017-10-03 at 16 42 42

**Comment by alanshaw** [comment]
I'm getting this in my logs @bmordan 

```
[2017-10-03 16:46:47] ERROR `/content/images/2014/Feb/meteor_london_2014_02_loop_sml.jpg' not found.
[2017-10-03 16:46:47] ERROR `/content/images/2014/Feb/meteor_london_2014_02_fin_sml.jpg' not found.
[2017-10-03 16:46:47] ERROR `/content/images/2014/Feb/meteor_london_2014_02_gumbyman_sml.jpg' not found.
```

**Comment by olizilla** [comment]
I LOVE THIS! The style looks great and it works nice.

Snags for the list

- [x] http://localhost:4000/test-the-ideas doesn't appear on the live blog, but does on the new one. It'd fine to include it, but it's attributed to olizilla but I'm pretty sure alanshaw wrote it, so maybe i was testing out keeping a post as a draft or something.
- [x] Some links in posts assumed assumed auto-linking would be enabled. I'm not sure jekyll makes that easy... I seem to recall we have to write plain urls with angle-brackets around them to get whatever markdown parser it's using to linkify links... see the links at the bottom of http://localhost:4000/tune-ing-super-fast-static-websites
- [x] Link color is needs a little more contrast to help people know they are clickable
- [x] Inline code style is a little too different from the body text, so it makes it hard for my eyeballs to track the sentences.

I'm pretty fond of the colors for links and inline codes in our doc styles:

| blog | docs |
| ----|-------|
| screenshot 2017-10-04 10 25 23 |  screenshot 2017-10-04 10 25 34 |

- [x] a little more vertical space before post title in a blog post
- [x] a little more vertical space around `hr`s (which are very cool)

👍 👍 👍

**Comment by bmordan** [comment]
screen shot 2017-10-05 at 11 58 35

**Comment by bmordan** [comment]
screen shot 2017-10-05 at 13 16 44

**Review by alanshaw — APPROVED** [review]

**Pull request merged**
